### ISSUE TITLE
Can this library be used in WIN? 

### ISSUE THREAD

**Issue by zhanghongyong123456** [xiumingzhang/xiuminglib#38]
Recently I have been trying to run this project of yours
https://github.com/google/neural-light-transport
I am not familiar with Blender, so I have some doubts. I hope you can reply to the question in this project
https://github.com/google/neural-light-transport/issues/4
I hope you can reply
Looking forward to your reply

**Comment by xiumingzhang** [comment]
See https://github.com/google/neural-light-transport/issues/4.
